### ISSUE TITLE
Надо использовать Container из вашей библиотеки, а не заглушку

### ISSUE THREAD

**Issue by coursar** [AliAlievALive/proggerHub#1]
https://github.com/AliAlievALive/proggerHub/blob/5830fdd537a1a5d613e3cbab89abe916bea88075/src/main/java/tech/itpark/proggerhub/Main.java#L12

**Comment by AliAlievALive** [comment]
Не дает установить зависимость Cannot resolve tech.itpark:di:1.2. Что я неправильно делаю?

**Comment by AliAlievALive** [comment]
Перепробовал разные способы, не дает установить зависимость от моего пакета. Что я делаю не так?

**Comment by coursar** [comment]
Что пишет? `settings.xml` сделали?

**Comment by AliAlievALive** [comment]
> Что пишет? `settings.xml` сделали?

Сделал, он и библиотеку скачивает, но внутри похоже нет исполняемых файлов

**Comment by coursar** [comment]
Что значит нет исполняемых файлов? Должен скачиваться jar'ник, а в jar'нике ваш контейнер. Заскриншотьте, что у вас в External Libraries в открытом виде?

**Comment by AliAlievALive** [comment]
> Что значит нет исполняемых файлов? Должен скачиваться jar'ник, а в jar'нике ваш контейнер. Заскриншотьте, что у вас в External Libraries в открытом виде?

![Снимок экрана 2021-04-01 в 08 34 04](https://user-images.githubusercontent.com/41789291/113248236-2f9d9080-92c5-11eb-9dd8-e3d73b8350c9.png)

**Comment by coursar** [comment]
Ok, разберёмся сегодня

**Comment by AliAlievALive** [comment]
> Ok, разберёмся сегодня

В итоге сегодня будет занятие?

**Comment by AliAlievALive** [comment]
Очередная попытка не увенчалась успехом
